eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: zuulservice
  profiles:
    active:
      default

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

server:
  port: 5555

management:
  endpoints:
    web:
      exposure:
        include: routes

zuul:
  ignored-services: memberservice, orderservice
  prefix: /api
  routes:
    memberservice: /my-member/**
    orderservice: /my-order/**