spring:
  application:
    name: fooservice
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://127.0.0.1:8888


management:
  endpoints:
    web:
      exposure:
        include: refresh
