server:
  port: 8081

spring:
  application:
    name: memberservice
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.sleuth: DEBUG
