server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sup2is/config-repo
          searchPaths: fooservice
          #username: native-cloud-apps
          #password: 0ffended