server:
  port: 8082

spring:
  application:
    name: orderservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
